In [1]:
import pandas as pd 
import matplotlib.pyplot as plt
import numpy as np
from sklearn import linear_model

In [26]:
df= pd.read_csv('homeprices.csv')
df.bedrooms.median()

np.float64(4.0)

In [32]:
df.bedrooms.fillna(df.bedrooms.median())
df['bedrooms'] =df.bedrooms.fillna(df.bedrooms.median())
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [4]:
df.columns

NameError: name 'df' is not defined

In [ ]:
%matplotlib inline
plt.scatter(df[[)

In [31]:
reg = linear_model.LinearRegression()
reg.fit(df[['area','bedrooms','age']],df.price)

LinearRegression()

In [19]:
reg.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [20]:
reg.predict([[3000,3,40]])

C:\Users\Atharva\AppData\Roaming\Python\Python311\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([498408.25158031])

In [33]:
reg.predict([[2500,4,5]])

C:\Users\Atharva\AppData\Roaming\Python\Python311\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([578876.03748933])

In [35]:
pip install word2number


Defaulting to user installation because normal site-packages is not writeable
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
  Created wheel for word2number: filename=word2number-1.1-py3-none-any.whl size=5589 sha256=5b6a668626b2680584ff6f7b5d4d005997da62f1a8cc6f9068c681a588203cfe
  Stored in directory: c:\users\atharva\appdata\local\pip\cache\wheels\cd\ef\ae\073b491b14d25e2efafcffca9e16b2ee6d114ec5c643ba4f06
Successfully built word2number
Note: you may need to restart the kernel to use updated packages.


In [37]:
import pandas as pd
import matplotlib.pyplot as plt
from word2number import w2n
from sklearn import linear_model

In [40]:
df = pd.read_csv('hiring.csv')
df


experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [41]:
df.experience.fillna('zero')

0      zero
1      zero
2      five
3       two
4     seven
5     three
6       ten
7    eleven
Name: experience, dtype: object

In [42]:
df.experience =df.experience.fillna('zero')

In [43]:
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0       zero                    8.0                           9      50000
1       zero                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [45]:
def word_to_number(text):
    try: 
        return w2n.word_to_num(text)
    except ValueError:
        return text
        

In [51]:
df['experience']= df['experience'].apply(word_to_number)

In [93]:
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    8.0                           7      60000
3           2                    8.0                          10      65000
4           7                    8.0                           6      70000
5           3                    8.0                          10      62000
6          10                    8.0                           7      72000
7          11                    8.0                           8      80000

In [92]:
df


experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    8.0                           7      60000
3           2                    8.0                          10      65000
4           7                    8.0                           6      70000
5           3                    8.0                          10      62000
6          10                    8.0                           7      72000
7          11                    8.0                           8      80000

In [71]:
df.columns

Index(['experience', 'test_score(out of 10)', 'interview_score(out of 10)',
       'salary($)'],
      dtype='object')

In [85]:
import math
median_test_score = math.floor(df['test_score(out of 10)'].mean())
median_test_score

8

In [87]:
d['test_score(out of 10)'] = d['test_score(out of 10)'].fillna(median_test_score)


In [88]:
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    8.0                           7      60000
3           2                    8.0                          10      65000
4           7                    8.0                           6      70000
5           3                    8.0                          10      62000
6          10                    8.0                           7      72000
7          11                    8.0                           8      80000

In [83]:
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    8.0                           7      60000
3           2                    8.0                          10      65000
4           7                    8.0                           6      70000
5           3                    8.0                          10      62000
6          10                    8.0                           7      72000
7          11                    8.0                           8      80000